### ISSUE TITLE
Sprint Report

### ISSUE THREAD

**Issue by espositoandrea** [F-S-C/Cicerone#22]
A causa del non funzionamento della piattaforma RedMine su cui il team si organizzava e lavorava, si sposta qui su GitHub parte delle segnalazioni ancora aperte.

Questa segnalazione è riguardante lo Sprint Report (in tutte le varie versioni successive alla creazione dell'issue).

Quando la prima piattaforma tornerà online si continuerà a lavorare lì. Fino ad allora sarà questa la piattaforma di riferimento.

**Comment by ReginaZaccaria** [comment]
**Inserimento documenti Sprint Report**


- _[Word] Sprint report (v 1.30)_ : [FSC_SRR.docx](https://github.com/F-S-C/Cicerone/files/3491944/FSC_SRR.docx)
- _[PDF] Sprint report (v 1.30)_ :  [FSC_SRR.pdf](https://github.com/F-S-C/Cicerone/files/3491945/FSC_SRR.pdf)
- _File JPG relativo al sonar qube measures (v 1.0)_ : ![sonarqube_measures](https://user-images.githubusercontent.com/44800243/62860147-84ab1e00-bcff-11e9-823f-4a30551e187a.JPG)
- _File JPG relativo al sonar qube overview(v 1.0)_ : ![sonarqube_overview](https://user-images.githubusercontent.com/44800243/62860148-84ab1e00-bcff-11e9-9d93-f34ddc348b34.JPG)
- _[ZIP] Codice sorgente ( v 1.15 )_ : In quanto il file supera i 25 MB, si allega il link del codice sorgente https://drive.google.com/open?id=1DbPyr-4XMCGlJ6qSK10lJNOcZxD6AKfz

**Comment by ReginaZaccaria** [comment]
Redmine sta funzionando nuovamente. È stato possibile caricate tutti i file mancanti.

**Comment by espositoandrea** [comment]
Questa Issue sarà utilizzata per lo _Sprint Report_ nel caso in cui RedMine dovesse nuovamente smettere di funzionare.

Si predispone di seguito un esempio di impostazione di un commento futuro (si riporta il codice e la preview grafica) utilizzabile sia per questa Issue che per tutte le issue legate a RedMine.

## Codice

```
# Sprint X

Breve nota opzionale.

<dl>
    <dt>Tempo impiegato (ore)</dt>
    <dd>X</dd>
    <dt>Versione</dt>
    <dd>1.x</dd>
</dl>

## File allegati

- `NomeFile1.ext` (v. 1.x): breve descrizione del file. [Link al file](#) 
- `NomeFile2.ext` (v. 1.x): breve descrizione del file. [Link al file](#)

## Codice sorgente

- `CodiceSorgente.zip` (v. 1.x): breve descrizione del file. [Link al file](#)
- `SonarQube (1).jpg` (v. 1.x): breve descrizione del file. [Link al file](#)
- `SonarQube (2).jpg` (v. 1.x): breve descrizione del file. [Link al file](#)
```

## Preview

> # Sprint X
> 
> Breve nota opzionale.
> 
> <dl>
>     <dt>Tempo impiegato (ore)</dt>
>     <dd>X</dd>
>     <dt>Versione</dt>
>     <dd>1.x</dd>
> </dl>
> 
> ## File allegati
> 
> - `NomeFile1.ext` (v. 1.x): breve descrizione del file. [Link al file](#) 
> - `NomeFile2.ext` (v. 1.x): breve descrizione del file. [Link al file](#)
> 
> ## Codice sorgente
> 
> - `CodiceSorgente.zip` (v. 1.x): breve descrizione del file. [Link al file](#)
> - `SonarQube (1).jpg` (v. 1.x): breve descrizione del file. [Link al file](#)
> - `SonarQube (2).jpg` (v. 1.x): breve descrizione del file. [Link al file](#)

**Comment by espositoandrea** [comment]
In quanto la piattaforma RedMine è nuovamente off-line, si riapre questa Issue.
