### ISSUE TITLE
Product Backlog

### ISSUE THREAD

**Issue by espositoandrea** [F-S-C/Cicerone#25]
Poiché la piattaforma RedMine è nuovamente offline, si crea questa Issue per sostituire la segnalazione riguardante il Product Backlog.

**Comment by ReginaZaccaria** [comment]
Aggiornamento del product backlog. È stato inserito l'item funzionale riguardante l'admin per permettergli di visualizzare la lista degli utenti registrati, è stato aggiornato l'indice del documento. Inoltre, è stato rimosso un item ridondante.

<dl>
    <dt>Tempo impiegato (ore)</dt>
    <dd>1.00</dd>
    <dt>Versione</dt>
    <dd>1.4</dd>
</dl>

## File allegati

- `FSC_PB.docx` (v. 1.4): [WORD] Product Backlog. [FSC_PB.docx](https://github.com/F-S-C/Cicerone/files/3519492/FSC_PB.docx)
- `FSC_PB.pdf` (v. 1.4): [PDF] Product Backlog. [FSC_PB.pdf](https://github.com/F-S-C/Cicerone/files/3519491/FSC_PB.pdf)
